Create README_ES.md
awslabs/aws-mobile-react-native-starter pull request #63
Opened 2018-02-20 03:56 UTC by LuigiBaute

If you got any suggestions on what to change I'll gladly change it as many times as necesary. :)

2018-02-21 15:47 UTC, LuigiBaute commented
Hi @elorzafe have you checked the Pull Request? Got any suggestions on the file? I'll gladly change it as many times as necessary :)

2018-02-22 15:43 UTC, LuigiBaute commented
Hi! @elorzafe @UnleashedMind did you guys liked the PR? Do you want me to change something? let me know! :+1:

2018-02-22 17:14 UTC, elorzafe commented
Hi @LuigiBaute thanks for your PR, I was reading your changes. Today I will finish my comments to it.

Thanks again!

2018-02-23 13:53 UTC, LuigiBaute commented
Hola @elorzafe , ¿Alguna sugerencia sobre la traducción? hazmelo saber! la modificare las veces que sean necesarias! :+1:

2018-02-24 03:26 UTC, elorzafe requested changes
Muchisimas gracias por tu aporte!!

Solo agregué algunos comentarios. Vamos a actualizar algunas secciones en la versión en inglés la próxima semana.

2018-02-24 03:26 UTC, elorzafe commented on Translation/ES/README_ES.md
> +Bootstrap una aplicación de React Native para AWS.
Yo diria: Bootstrap de una aplicación de React Native en AWS.

y eliminaria la linea 4 que dice lo mismo.

2018-02-24 03:26 UTC, elorzafe commented on Translation/ES/README_ES.md
> +autenticación, autorización, almacenamiento de imágenes, acceso API y
acceso a API

2018-02-24 03:26 UTC, elorzafe commented on Translation/ES/README_ES.md
> +soporte MFA. El caso de uso de muestra es un "Pet Tracker"el cual
agregaría un espacio despues de "Pet Tracker"

2018-02-24 03:26 UTC, elorzafe commented on Translation/ES/README_ES.md
> + - [Getting started](#getstarted)
Falta que los títulos también estén en español

2018-02-24 03:26 UTC, elorzafe commented on Translation/ES/README_ES.md
> +![Architecture](media/architecture.png)
el png deberia estar dentro del mismo directorio para que se vea? Nunca he usado el translate.

2018-02-24 03:26 UTC, elorzafe commented on Translation/ES/README_ES.md
> +Servicios AWS usados:
Servicios AWS utilizados:

2018-02-24 03:26 UTC, elorzafe commented on Translation/ES/README_ES.md
> +- AWS Account
Cuenta de AWS

2018-02-24 03:26 UTC, elorzafe commented on Translation/ES/README_ES.md
> +- [Node.js](https://nodejs.org/) with NPM
con NPM

2018-02-24 03:26 UTC, elorzafe commented on Translation/ES/README_ES.md
> +  - On macOS, it is recommended to install it using [Homebrew](https://brew.sh/)
On macOS, se recomienda para la instalación usar

2018-02-24 03:26 UTC, elorzafe commented on Translation/ES/README_ES.md
> +1. Crea tus recursos backend y descarga el código muestra dentro de la
Crea los servicios y descarga el código de ejemplo dentro del directorio my-project

2018-02-24 03:26 UTC, elorzafe commented on Translation/ES/README_ES.md
> +2. Finalmente inicia la aplicación:
Finalmente para iniciar la aplicación:

2018-02-24 03:26 UTC, elorzafe commented on Translation/ES/README_ES.md
> +primero transferirá la foto de una cubeta S3 a la cual sólo el usuario
primero transferirá la foto a una cubeta S3 a la cual sólo el usuario

2018-02-24 03:26 UTC, elorzafe commented on Translation/ES/README_ES.md
> +![Add Pet](media/Nadia1.png)
lo mismo que más arriba, quizas hay que copiar todas las imagenes

2018-02-24 03:26 UTC, elorzafe commented on Translation/ES/README_ES.md
> +6. Verás un archivo de tu mascota en la pantalla de inicio.
Verás el registro de tu mascota en la pantalla de inicio.

2018-02-24 03:26 UTC, elorzafe commented on Translation/ES/README_ES.md
> +Esta aplicación de inicia usa la librería AWS Amplify para integrarse
Este iniciador usa la librería...

2018-02-24 03:26 UTC, elorzafe commented on Translation/ES/README_ES.md
> +- Descarga el archivo `aws-exports.js` de tu proyecto AWS MobileHub
Tenemos que actualizar eso con la información de awsmobile-cli, también para la versión en inglés

2018-02-24 03:26 UTC, elorzafe commented on Translation/ES/README_ES.md
> +5. Importa el módulo `Auth` de la librería y tus aws-exports aquí
Importa el módulo `Auth` de la librería y aws-exports aquí

2018-02-24 03:26 UTC, elorzafe commented on Translation/ES/README_ES.md
> +with MFA y Sign Out a tu aplicación out of the box. Podrías usar este
a tu aplicación directamente...

2018-02-24 03:26 UTC, elorzafe commented on Translation/ES/README_ES.md
> +necesitarás presentar tus pedidos usando el proceso de registro [AWS
necesitarás firmar tus HTTP request usando el proceso de firmado [AWS

2018-02-24 03:26 UTC, elorzafe commented on Translation/ES/README_ES.md
> +[Amplify](https://github.com/aws/aws-amplify) para hacer pedidos al
...para hacer HTTP request al

2018-02-24 03:26 UTC, elorzafe commented on Translation/ES/README_ES.md
> +AWS Credentials. También puedes hacer pedidos sin autenticar a tu API.
Esa parte no esta soportada por el momento en Amplify 
"También puedes hacer pedidos sin autenticar a tu API."

2018-02-24 03:26 UTC, elorzafe commented on Translation/ES/README_ES.md
> +importa awsmobile de './aws-exports';
import awsmobile from './aws-exports';

2018-02-24 03:26 UTC, elorzafe commented on Translation/ES/README_ES.md
> +importa Amplify, { API } de 'aws-amplify';
import Amplify, { API } from 'aws-amplify';

2018-02-24 03:26 UTC, elorzafe commented on Translation/ES/README_ES.md
> +7. Ahora puedes invocar APIs API Gateway desde tu React Native que son
...APIs en API Gateway desde tu aplicación en React Native ...

2018-02-24 03:26 UTC, elorzafe commented on Translation/ES/README_ES.md
> +protegidas vía  AWS IAM. Puedes usar otras llamadas REST como muestra
protegidas vía AWS IAM (espacio extra)

2018-02-24 03:26 UTC, elorzafe commented on Translation/ES/README_ES.md
> +El componente `Storage` requiere AWS Credentials para llamar el S3. Si
para llamar a Amazon S3

2018-02-24 03:26 UTC, elorzafe commented on Translation/ES/README_ES.md
> +necesitas almacenar datos en carpetas privadas a usuarios, necesitarás
..en directorios restringidos solo para el usuario...

2018-02-24 03:26 UTC, elorzafe commented on Translation/ES/README_ES.md
> +primero que completar la sección Auth. Por favor sigue los pasos de la
primero completar la sección Auth

2018-02-24 03:26 UTC, elorzafe commented on Translation/ES/README_ES.md
> +importa Amplify, { Storage } de 'aws-amplify'
import Amplify, { Storage } from 'aws-amplify';

2018-02-24 03:26 UTC, elorzafe commented on Translation/ES/README_ES.md
> +presentar los objetos balde PUT, GET, REMOVE and LIST. También se
acceder a los objetos del bucket tales como PUT, GET, REMOVE y LIST. También se

2018-02-24 03:26 UTC, elorzafe commented on Translation/ES/README_ES.md
> +especificado usando la opción `level` con la llamada.
especificado la opción...

2018-02-24 03:26 UTC, elorzafe commented on Translation/ES/README_ES.md
> +1. Después que has cloneado este repo, localiza
clonado

2018-02-24 03:26 UTC, elorzafe commented on Translation/ES/README_ES.md
> +encuentra la siguiente sección de código:
la siguiente sección en el código:

2018-02-24 03:26 UTC, elorzafe commented on Translation/ES/README_ES.md
> +2. Guarda el archivo y en la consola para tu proyecto Mobile Hub haz
Toda esta sección hay que actualizar con awsmobile-cli (también en Inglés)

2018-02-24 03:26 UTC, elorzafe commented on Translation/ES/README_ES.md
> +S3 está configurada por Mobile Hub para usar control de acceso fino
S3 está configurada por Mobile Hub para restringir el acceso y

2018-02-24 03:26 UTC, elorzafe commented on Translation/ES/README_ES.md
> +Para aprender más sobre restricción a este acceso, visita [Amazon S3
Para aprender más sobre restricción de acceso

2018-02-24 03:26 UTC, elorzafe commented on Translation/ES/README_ES.md
> +persistir localmente monedas de usuarios (accessKeyId, secretAccessKey
persistir localmente llaves de usuarios

2018-02-24 03:26 UTC, elorzafe commented on Translation/ES/README_ES.md
> +and sessionToken). Puedes tomar más acciones de seguridad mediante la
y sessionToken)...

2018-02-24 03:26 UTC, elorzafe commented on Translation/ES/README_ES.md
> +### API Handler Table Permissions
Controlador de API y permisos de las tablas

2018-02-24 07:05 UTC, LuigiBaute commented on Translation/ES/README_ES.md
> +![Architecture](media/architecture.png)
no toqué ese código, asi me apareció en el raw de la versión original

2018-02-27 18:09 UTC, LuigiBaute commented on Translation/ES/README_ES.md
> +AWS Credentials. También puedes hacer pedidos sin autenticar a tu API.
en este caso, ¿qué debería hacer? ¿elimino esta parte del texto?

2018-02-28 11:41 UTC, LuigiBaute commented on Translation/ES/README_ES.md
> +2. Guarda el archivo y en la consola para tu proyecto Mobile Hub haz
¿Qué debo colocar en su lugar? ¿la debería eliminar?

2018-03-02 03:47 UTC, closed without merging